name: Build

on:
  push:
    branches: [ main ]

    workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    env:
     PROJECT_PATH: ".\\"
     BUILD_METHOD_WIN64: "Build.BuildWindows64"
     BUILD_METHOD_WIN32: "Build.BuildWindows32"
     gamename: "SaveTheCircus"
     projectVersion:
       
    steps:
        - uses: actions/checkout@v2
        - name: Build For Windows 64 bits     
          run: Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe'-ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN64 -quit"
        - name: Build For Windows 32 bits
          run: Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe'-ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN32 -quit"
        - uses: actions/upload-artifact@v2
          with:
             name: SaveTheCircus
             path: Builds/*


